### ISSUE TITLE
sync_pending crashes on when there is no tx event as yet

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#69]
Traceback (most recent call last):
  File "robot_sync_pending_bets.py", line 69, in <module>
    processed_receipt = contract.events.NumberGeneratorQuery().processReceipt(tx_receipt)[0]
  File "/usr/local/lib/python3.6/dist-packages/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1279, in processReceipt
    return self._parse_logs(txn_receipt)
  File "/usr/local/lib/python3.6/dist-packages/eth_utils/functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1283, in _parse_logs
    for log in txn_receipt['logs']:
TypeError: 'NoneType' object is not subscriptable

**Comment by jparicka** [comment]
fixed
