### ISSUE TITLE
events listener frequently crashes on timeouts

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#84]
Listenting for these ETHEREUM_EVENT_TOPICS

         WinningNumber 0x03478d343c9c91598b90aa771d40bfc509b9c571c93585e1d80a7e46566846c3
         NumberGeneratorQuery 0x1bec31073981b1ab0d17d1a6a0d301ab377caea5c0fb8b6c4ee72817ce145ca9

Listenting for contract events....

Traceback (most recent call last):
  File "robot_sync_game_events.py", line 214, in <module>
    main()
  File "robot_sync_game_events.py", line 201, in main
    block_filter = w3.eth.filter({'toBlock': 'latest', 'address': settings.ETHEREUM_DICE_CONTRACT})
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 332, in filter
    [filter_params],
  File "/usr/local/lib/python3.5/dist-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.5/dist-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/websocket.py", line 119, in make_request
    return future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/websocket.py", line 107, in coro_make_request
    timeout=self.websocket_timeout
  File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by jparicka** [comment]
what the fuck?

https://ethereum.stackexchange.com/questions/16174/retrieving-logs-using-filter-is-not-working
