### ISSUE TITLE
import keys not working

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#96]
Loading master wallet..
Traceback (most recent call last):
  File "robot_topup_vusers_wallets.py", line 229, in <module>
    account_key = Account.decrypt(wallet_json, wallet_secret)
  File "/usr/local/lib/python3.6/dist-packages/eth_account/account.py", line 127, in decrypt
    return decode_keyfile_json(keyfile, password_bytes)
  File "/usr/local/lib/python3.6/dist-packages/eth_keyfile/keyfile.py", line 49, in decode_keyfile_json
    return _decode_keyfile_json_v3(keyfile_json, password)
  File "/usr/local/lib/python3.6/dist-packages/eth_keyfile/keyfile.py", line 159, in _decode_keyfile_json_v3
    derived_key = _derive_scrypt_key(crypto, password)
  File "/usr/local/lib/python3.6/dist-packages/eth_keyfile/keyfile.py", line 213, in _derive_scrypt_key
    buflen=buflen,
  File "/usr/local/lib/python3.6/dist-packages/eth_keyfile/keyfile.py", line 226, in _scrypt_hash
    num_keys=1,
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Protocol/KDF.py", line 404, in scrypt
    raise ValueError("Error %X while running scrypt" % result)
ValueError: Error 2 while running scrypt

**Comment by jparicka** [comment]
fixed
